# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
warnings_are_errors: false

after_success:
  - Rscript -e 'covr::codecov()'

script:
  - zip -r latest *
  - mkdir -p deployment
  - mv latest.zip deployment/latest.zip

deploy:
- provider: s3
  access_key_id: $AWS_ACCESS_ID
  secret_access_key: $AWS_SECRET_KEY
  local_dir: deployment
  skip_cleanup: true
  on: &2
    repo: ajeyamk/MSstatsConvert
  bucket: $AWS_S3_BUCKET
  region: $AWS_REGION
- provider: codedeploy
  access_key_id: $AWS_ACCESS_ID
  secret_access_key: $AWS_SECRET_KEY
  bucket: $AWS_S3_BUCKET
  key: latest.zip
  bundle_type: zip
  application: $AWS_DEPLOYMENT_NAME
  deployment_group: $AWS_DEPLOYMENT_NAME
  region: $AWS_REGION
  on: *1

after_deploy:
- cd /home/rstudio/code/deployment/tests
  chmod +x tests.R
  ./tests.R
